use std::{env, fs, path::PathBuf, process::ExitCode};

use kf_bitstream::SequenceHeader;
use kf_dec::FastDecoder;
use kf_enc::{Encoder, IntraEncoder};
use kf_frame::Frame;
use kf_ref::ReferenceDecoder;
use kf_tools::sha256_hex;

struct Vector {
    name: &'static str,
    width: u16,
    height: u16,
    qp: u8,
    source: Frame,
}

fn main() -> ExitCode {
    let check = env::args().nth(1).as_deref() == Some("--check");
    match generate(check) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("staging-conformance: {message}");
            ExitCode::from(1)
        }
    }
}

fn generate(check: bool) -> Result<(), String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .ok_or_else(|| "cannot locate repository root".to_owned())?
        .to_path_buf();
    let output_dir = root.join("conformance/staging");
    let vectors = vectors()?;
    let mut manifest = String::from(
        "format = \"key-frame-staging-v0\"\npre_freeze = true\nbitstream_version = 1\n\n",
    );
    let mut artifacts = Vec::new();
    for vector in vectors {
        let sequence = SequenceHeader::new(vector.width, vector.height, 24, 1, 120, 16)
            .map_err(|error| error.to_string())?;
        let encoded = IntraEncoder::new(sequence, vector.qp)
            .map_err(|error| error.to_string())?
            .encode(std::slice::from_ref(&vector.source))
            .map_err(|error| error.to_string())?;
        let decoded = FastDecoder::new()
            .decode_intra_stream(&encoded.bytes)
            .map_err(|error| error.to_string())?
            .remove(0);
        let decoded_yuv = raw_yuv(&decoded);
        if vector.name.contains("gradient") && decoded_yuv == raw_yuv(&vector.source) {
            return Err("gradient staging decode matched the unfiltered source".to_owned());
        }
        let file_name = format!("{}.kfv", vector.name);
        manifest.push_str(&format!(
            "[[vectors]]\nname = \"{}\"\nstream = \"{}\"\nwidth = {}\nheight = {}\nqp = {}\nstream_sha256 = \"{}\"\ndecoded_yuv_sha256 = \"{}\"\n\n",
            vector.name,
            file_name,
            vector.width,
            vector.height,
            vector.qp,
            sha256_hex(&encoded.bytes),
            sha256_hex(&decoded_yuv),
        ));
        artifacts.push((output_dir.join(file_name), encoded.bytes));
    }
    let inter_sources = inter_sources()?;
    let inter_sequence =
        SequenceHeader::new(64, 64, 24, 1, 120, 2).map_err(|error| error.to_string())?;
    let inter_encoded = Encoder::new(inter_sequence, 32)
        .map_err(|error| error.to_string())?
        .encode(&inter_sources)
        .map_err(|error| error.to_string())?;
    let inter_decoded = FastDecoder::new()
        .decode_stream(&inter_encoded.bytes)
        .map_err(|error| error.to_string())?;
    let independent = ReferenceDecoder::new()
        .decode_stream(&inter_encoded.bytes)
        .map_err(|error| error.to_string())?;
    if inter_decoded != independent || inter_decoded != inter_encoded.reconstructed_frames {
        return Err("inter staging stream disagrees across closed loop and decoders".to_owned());
    }
    let decoded_bytes = inter_decoded.iter().flat_map(raw_yuv).collect::<Vec<_>>();
    let inter_file = "inter_motion64_qp32.kfv";
    manifest.push_str(&format!(
        "[[vectors]]\nname = \"inter_motion64_qp32\"\nstream = \"{inter_file}\"\nwidth = 64\nheight = 64\nframe_count = 3\nqp = 32\nfeatures = [\"p_frame\", \"motion\", \"reference_refresh\", \"context_carry\"]\nstream_sha256 = \"{}\"\ndecoded_yuv_sha256 = \"{}\"\n\n",
        sha256_hex(&inter_encoded.bytes),
        sha256_hex(&decoded_bytes),
    ));
    artifacts.push((output_dir.join(inter_file), inter_encoded.bytes));
    artifacts.push((output_dir.join("manifest.toml"), manifest.into_bytes()));
    if check {
        for (path, expected) in artifacts {
            let actual = fs::read(&path).map_err(|error| format!("{}: {error}", path.display()))?;
            if actual != expected {
                return Err(format!(
                    "{} drifted; regenerate staging vectors",
                    path.display()
                ));
            }
        }
        println!("staging-conformance: OK — regenerated bytes and decoded hashes match");
    } else {
        fs::create_dir_all(&output_dir).map_err(|error| error.to_string())?;
        for (path, contents) in artifacts {
            fs::write(&path, contents).map_err(|error| format!("{}: {error}", path.display()))?;
        }
        println!("staging-conformance: wrote {}", output_dir.display());
    }
    Ok(())
}

fn vectors() -> Result<Vec<Vector>, String> {
    let neutral = Frame::filled_420(64, 64, 128).map_err(|error| error.to_string())?;
    let mut gradient = Frame::filled_420(66, 64, 0).map_err(|error| error.to_string())?;
    for y in 0..64 {
        for x in 0..66 {
            gradient
                .y
                .set(x, y, u8::try_from((x * 3 + y * 2) % 256).unwrap())
                .map_err(|error| error.to_string())?;
        }
    }
    Ok(vec![
        Vector {
            name: "neutral64_qp28",
            width: 64,
            height: 64,
            qp: 28,
            source: neutral,
        },
        Vector {
            name: "gradient66x64_qp32",
            width: 66,
            height: 64,
            qp: 32,
            source: gradient,
        },
    ])
}

fn inter_sources() -> Result<Vec<Frame>, String> {
    let mut first = Frame::filled_420(64, 64, 96).map_err(|error| error.to_string())?;
    for y in 0..64 {
        for x in 0..64 {
            first
                .y
                .set(x, y, u8::try_from((x * 5 + y * 3) % 256).unwrap())
                .map_err(|error| error.to_string())?;
        }
    }
    let mut second = first.clone();
    let mut third = first.clone();
    for y in 0..64 {
        for x in 0..64 {
            second
                .y
                .set(x, y, first.y.get(x.saturating_sub(1), y).unwrap())
                .map_err(|error| error.to_string())?;
            third
                .y
                .set(x, y, first.y.get(x.saturating_sub(2), y).unwrap())
                .map_err(|error| error.to_string())?;
        }
    }
    Ok(vec![first, second, third])
}

fn raw_yuv(frame: &Frame) -> Vec<u8> {
    let mut bytes =
        Vec::with_capacity(frame.y.data().len() + frame.cb.data().len() + frame.cr.data().len());
    bytes.extend_from_slice(frame.y.data());
    bytes.extend_from_slice(frame.cb.data());
    bytes.extend_from_slice(frame.cr.data());
    bytes
}
