#!/usr/bin/env bash
#
# The local mirror of CI. Run this before opening a change; it is the same set
# of checks the `check` workflow runs, in the same order, so a red pipeline is
# something you already saw on your own machine.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

echo "[1/34] version coherence"
node "$repo_root/scripts/check-version-coherence.mjs"
echo "[2/34] documentation coherence"
"$repo_root/scripts/ci/doc-coherence.sh"
echo "[3/34] claim coherence"
"$repo_root/scripts/ci/claims-coherence.sh"
echo "[4/34] interface coherence"
"$repo_root/scripts/ci/interface-coherence.mjs"
echo "[5/34] declared scalar use"
"$repo_root/scripts/ci/declared-scalar-use.sh"
echo "[6/34] license coherence"
"$repo_root/scripts/ci/license-coherence.sh"
echo "[7/34] dependency closure"
"$repo_root/scripts/ci/dependency-closure.sh"
echo "[8/34] specification closure"
"$repo_root/scripts/ci/spec-check.sh"
echo "[9/34] range-coder gate"
"$repo_root/scripts/ci/range-gate.sh"
echo "[10/34] transform and quantization gate"
"$repo_root/scripts/ci/transform-gate.sh"
echo "[11/34] bitstream header and packet gate"
"$repo_root/scripts/ci/bitstream-gate.sh"
echo "[12/34] syntax round-trip gate"
"$repo_root/scripts/ci/syntax-gate.sh"
echo "[13/34] independent reference decoder gate"
"$repo_root/scripts/ci/reference-gate.sh"
echo "[14/34] probe schema and canonical replay gate"
"$repo_root/scripts/ci/probe-gate.sh"
echo "[15/34] end-to-end intra codec gate"
"$repo_root/scripts/ci/intra-gate.sh"
echo "[16/34] native conformance gate"
"$repo_root/scripts/ci/conformance-gate.sh"
echo "[17/34] inter codec gate"
"$repo_root/scripts/ci/inter-gate.sh"
echo "[18/34] entropy lockstep and transaction gate"
"$repo_root/scripts/ci/entropy-gate.sh"
echo "[19/34] deblock filter gate"
"$repo_root/scripts/ci/deblock-gate.sh"
echo "[20/34] natural corpus bit-exactness gate"
"$repo_root/scripts/ci/corpus-gate.sh"
echo "[21/34] rate-control gate"
"$repo_root/scripts/ci/rate-gate.sh"
echo "[22/34] quality-metric gate"
"$repo_root/scripts/ci/metric-gate.sh"
echo "[23/34] rate-distortion receipt gate"
"$repo_root/scripts/ci/rd-gate.sh"
echo "[24/34] decoder campaign gate"
"$repo_root/scripts/ci/fuzz-gate.sh"
echo "[25/34] corruption and error matrix gate"
"$repo_root/scripts/ci/error-matrix-gate.sh"
echo "[26/34] conformance coverage gate"
"$repo_root/scripts/ci/coverage-gate.sh"
echo "[27/34] random-access seek gate"
"$repo_root/scripts/ci/seek-gate.sh"
echo "[28/34] native and WebAssembly equality gate"
"$repo_root/scripts/ci/wasm-gate.sh"
echo "[29/34] projection room build, budget, and browser smoke"
"$repo_root/scripts/ci/site-gate.sh"
echo "[30/34] cargo fmt"
cargo fmt --all -- --check
echo "[31/34] cargo clippy"
cargo clippy --locked --workspace --all-targets -- -D warnings
echo "[32/34] forbidden API scan and decoder boundary"
"$repo_root/scripts/ci/forbidden-grep.sh"
echo "[33/34] tests"
cargo test --locked --workspace --all-targets
echo "[34/34] rustdoc"
cargo doc --locked --workspace --no-deps
echo "preflight: PASS"
