#!/usr/bin/env bash
#
# The local mirror of CI. Run this before opening a change; it is the same set
# of checks the `check` workflow runs, in the same order, so a red pipeline is
# something you already saw on your own machine.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

echo "[1/32] version coherence"
node "$repo_root/scripts/check-version-coherence.mjs"
echo "[2/32] documentation coherence"
"$repo_root/scripts/ci/doc-coherence.sh"
echo "[3/32] claim coherence"
"$repo_root/scripts/ci/claims-coherence.sh"
echo "[4/32] declared scalar use"
"$repo_root/scripts/ci/declared-scalar-use.sh"
echo "[5/32] license coherence"
"$repo_root/scripts/ci/license-coherence.sh"
echo "[6/32] specification closure"
"$repo_root/scripts/ci/spec-check.sh"
echo "[7/32] range-coder gate"
"$repo_root/scripts/ci/range-gate.sh"
echo "[8/32] transform and quantization gate"
"$repo_root/scripts/ci/transform-gate.sh"
echo "[9/32] bitstream header and packet gate"
"$repo_root/scripts/ci/bitstream-gate.sh"
echo "[10/32] syntax round-trip gate"
"$repo_root/scripts/ci/syntax-gate.sh"
echo "[11/32] independent reference decoder gate"
"$repo_root/scripts/ci/reference-gate.sh"
echo "[12/32] probe schema and canonical replay gate"
"$repo_root/scripts/ci/probe-gate.sh"
echo "[13/32] end-to-end intra codec gate"
"$repo_root/scripts/ci/intra-gate.sh"
echo "[14/32] native conformance gate"
"$repo_root/scripts/ci/conformance-gate.sh"
echo "[15/32] inter codec gate"
"$repo_root/scripts/ci/inter-gate.sh"
echo "[16/32] entropy lockstep and transaction gate"
"$repo_root/scripts/ci/entropy-gate.sh"
echo "[17/32] deblock filter gate"
"$repo_root/scripts/ci/deblock-gate.sh"
echo "[18/32] natural corpus bit-exactness gate"
"$repo_root/scripts/ci/corpus-gate.sh"
echo "[19/32] rate-control gate"
"$repo_root/scripts/ci/rate-gate.sh"
echo "[20/32] quality-metric gate"
"$repo_root/scripts/ci/metric-gate.sh"
echo "[21/32] rate-distortion receipt gate"
"$repo_root/scripts/ci/rd-gate.sh"
echo "[22/32] decoder campaign gate"
"$repo_root/scripts/ci/fuzz-gate.sh"
echo "[23/32] corruption and error matrix gate"
"$repo_root/scripts/ci/error-matrix-gate.sh"
echo "[24/32] conformance coverage gate"
"$repo_root/scripts/ci/coverage-gate.sh"
echo "[25/32] random-access seek gate"
"$repo_root/scripts/ci/seek-gate.sh"
echo "[26/32] native and WebAssembly equality gate"
"$repo_root/scripts/ci/wasm-gate.sh"
echo "[27/32] projection room build, budget, and browser smoke"
"$repo_root/scripts/ci/site-gate.sh"
echo "[28/32] cargo fmt"
cargo fmt --all -- --check
echo "[29/32] cargo clippy"
cargo clippy --locked --workspace --all-targets -- -D warnings
echo "[30/32] forbidden API scan and decoder boundary"
"$repo_root/scripts/ci/forbidden-grep.sh"
echo "[31/32] tests"
cargo test --locked --workspace --all-targets
echo "[32/32] rustdoc"
cargo doc --locked --workspace --no-deps
echo "preflight: PASS"
