#!/usr/bin/env bash
#
# The local mirror of CI. Run this before opening a change; it is the same set
# of checks the `check` workflow runs, in the same order, so a red pipeline is
# something you already saw on your own machine.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

echo "[1/29] version coherence"
node "$repo_root/scripts/check-version-coherence.mjs"
echo "[2/29] documentation coherence"
"$repo_root/scripts/ci/doc-coherence.sh"
echo "[3/29] license coherence"
"$repo_root/scripts/ci/license-coherence.sh"
echo "[4/29] specification closure"
"$repo_root/scripts/ci/spec-check.sh"
echo "[5/29] range-coder gate"
"$repo_root/scripts/ci/range-gate.sh"
echo "[6/29] transform and quantization gate"
"$repo_root/scripts/ci/transform-gate.sh"
echo "[7/29] bitstream header and packet gate"
"$repo_root/scripts/ci/bitstream-gate.sh"
echo "[8/29] syntax round-trip gate"
"$repo_root/scripts/ci/syntax-gate.sh"
echo "[9/29] independent reference decoder gate"
"$repo_root/scripts/ci/reference-gate.sh"
echo "[10/29] probe schema and canonical replay gate"
"$repo_root/scripts/ci/probe-gate.sh"
echo "[11/29] end-to-end intra codec gate"
"$repo_root/scripts/ci/intra-gate.sh"
echo "[12/29] native conformance gate"
"$repo_root/scripts/ci/conformance-gate.sh"
echo "[13/29] inter codec gate"
"$repo_root/scripts/ci/inter-gate.sh"
echo "[14/29] entropy lockstep and transaction gate"
"$repo_root/scripts/ci/entropy-gate.sh"
echo "[15/29] deblock filter gate"
"$repo_root/scripts/ci/deblock-gate.sh"
echo "[16/29] natural corpus bit-exactness gate"
"$repo_root/scripts/ci/corpus-gate.sh"
echo "[17/29] rate-control gate"
"$repo_root/scripts/ci/rate-gate.sh"
echo "[18/29] quality-metric gate"
"$repo_root/scripts/ci/metric-gate.sh"
echo "[19/29] decoder campaign gate"
"$repo_root/scripts/ci/fuzz-gate.sh"
echo "[20/29] corruption and error matrix gate"
"$repo_root/scripts/ci/error-matrix-gate.sh"
echo "[21/29] conformance coverage gate"
"$repo_root/scripts/ci/coverage-gate.sh"
echo "[22/29] random-access seek gate"
"$repo_root/scripts/ci/seek-gate.sh"
echo "[23/29] native and WebAssembly equality gate"
"$repo_root/scripts/ci/wasm-gate.sh"
echo "[24/29] projection room build, budget, and browser smoke"
"$repo_root/scripts/ci/site-gate.sh"
echo "[25/29] cargo fmt"
cargo fmt --all -- --check
echo "[26/29] cargo clippy"
cargo clippy --locked --workspace --all-targets -- -D warnings
echo "[27/29] forbidden API scan and decoder boundary"
"$repo_root/scripts/ci/forbidden-grep.sh"
echo "[28/29] tests"
cargo test --locked --workspace --all-targets
echo "[29/29] rustdoc"
cargo doc --locked --workspace --no-deps
echo "preflight: PASS"
